### ISSUE TITLE
How am I supposed to importStack if I can't save the [Stroke] as NSData?

### ISSUE THREAD

**Issue by Sweeper777** [dehli/TouchDraw#11]
The `importStack` and `exportStack` methods I guess are used to save drawings that users draw, right? But how to save the exported `[Stroke]`. I can't save it in `NSUserDefaults` because it is not a property list. I can't save it in Core Data because it can't be converted into `NSData` using `NSKeyedArchiver`:

    let stack = drawView.exportStack()
    let data = NSKeyedArchiver.archivedDataWithRootObject(stack)

How am I supposed to save the stack?

**Comment by dehli** [comment]
So for my testing I was just using it to import the stack into a new view
controller  (so the stack was just being stored in memory). I'll modify the
functions so that they can also be saved in storage. Thanks for all the
feedback you've given! I really appreciate it!

**Comment by dehli** [comment]
Hi @Sweeper777, I wanted to give you an update. I've tried making the Stroke object inherit from `NSObject` and `NSCoding` but I'm still getting an error. It's all been pushed to the development branch if you wanted to see what I've tried. Hopefully I'll figure it out soon.

**Comment by Sweeper777** [comment]
I think `CIColor` can't be encoded? Maybe you should turn it into a hex string first.

**Comment by dehli** [comment]
Hey @Sweeper777, I have it exporting the stack now without crashing! I just need to do some testing to make sure that it's actually persistant. Thanks for your patience!

**Comment by dehli** [comment]
This has been fixed with Release `1.3.1`.  Let me know if you have any issues please!
