### ISSUE TITLE
Cocoa pod v 1.3.1 Missing Files

### ISSUE THREAD

**Issue by liltimtim** [dehli/TouchDraw#15]
Hello,

When I ran pod update I noticed a new version of TouchDraw had been published. 

After updated to 1.3.1 I was unable to compile due to missing files.  Specifically where "Stroke" is defined. 

I uninstalled the pod file and forced version 1.3.0 to be installed and the project compiled fine again.  

I believe it's probably a reference issue in the pod spec file or something related to that.  

Cheers,
TB

**Comment by dehli** [comment]
Thanks for letting me know! I refactored the code so that there were 3 files instead of just the one. I'll try to figure out what the issue is tonight and push it. Sorry!

**Comment by liltimtim** [comment]
No problem!  I am grateful that this library exists in the first place!  It has saved me a lot of headache!

**Comment by dehli** [comment]
Hey, I just created a demo project and created a podfile referencing `TouchDraw` version `1.3.1`. It ran fine for me. Can you try again? Maybe try removing the pods folder and redownloading?

**Comment by liltimtim** [comment]
So to fix it, I had to remove the pod by commenting out the TouchDraw.  Place the TouchDraw pod back into the pod file. Run pod install and it seems to fix it.

**Comment by dehli** [comment]
Awesome! Glad it's working for you!
