### ISSUE TITLE
Hello! Hide problem and ScrollView

### ISSUE THREAD

**Issue by Sk8er22** [dehli/TouchDraw#24]
First of all Thanks for your work, I have two problems:

1) If is hide and later i make it appear, doesn't works
2) inside a scroll view, not works properly, what should i do?

**Comment by dehli** [comment]
Hey @Sk8er22! Thanks for bringing these issues up. I'll investigate them later today and update you!

**Comment by dehli** [comment]
Hey, sorry my summer semester was wrapping up so I was pretty busy. 

If you hide the `TouchDrawView`, and make it appear again what doesn't work? Are there any error messages? Can you draw new lines?

Also in a scroll view, how is it not working properly? Is it preventing you from scrolling? Are the drawings not turning up properly?

If you could attach screenshots, that would be great! Also a simple project showcasing the errors you're finding would be appreciated. Thanks!

**Comment by dehli** [comment]
Closing this issue due to a lack of response. Please feel free to reopen with more details! Thanks.
