### ISSUE TITLE
Clearing / erasing

### ISSUE THREAD

**Issue by ggschelling** [dehli/TouchDraw#30]
Is there a possibility to remove/erase (like a rubber) the drawing? First I thought clearEnabled() does the trick, but after calling clearEnabled() nothing changes (it continue to draw in colors). Maybe I have to do anything else than just switch between clearEnabled() and clearDisabled() ... ?

**Comment by dehli** [comment]
`clearEnabled` is a callback that's called when you should be able to clear or not (basically there are strokes in the view). If you want to use the eraser you need to call: 

```
setColor(nil)
```

This was added in version 2.1.0. Let me know if that doesn't work for you.
