### ISSUE TITLE
Changing portrait to landscape and drawing is not showing properly 

### ISSUE THREAD

**Issue by goodsw4all** [dehli/TouchDraw#33]
Firstly thanks for your great work.

Like attached pictures, I found a bug.
So, I hope you have a chance to check it.
Or, advice on which part should I look into.

How to duplicate: Draw something and change the rotation then Draw something again
Result is shown below.
![image](https://user-images.githubusercontent.com/1715346/40869416-aabeb2fc-6655-11e8-928f-4713d6b3c6a5.png)

![image](https://user-images.githubusercontent.com/1715346/40869424-c11cf392-6655-11e8-8806-331c409b8781.png)

Thank you in advance !!!
Have a good one !!

**Comment by dehli** [comment]
Hey, this has been fixed on master I believe! I am refactoring a little bit of the code before I release a new version, but you should be able to point to the latest SHA for the time being. Let me know if that works!

**Comment by dehli** [comment]
Hello! I just pushed up a release on CocoaPods (2.1.2) that should fix this. Thanks for creating the issue! I'll close the issue for now, but feel free to reopen it if you still see the issue after upgrading! Thanks! 😄

**Comment by goodsw4all** [comment]
I got Pod updated and tested it.
I worked well.
Thank you !!!
