### ISSUE TITLE
Image issue

### ISSUE THREAD

**Issue by junestchick** [dehli/TouchDraw#34]
It also removes image if I call undo(). Pls fix this.

**Comment by junestchick** [comment]
Hi, thanks for reply, TouchDrawView is a subclass of UIImageView, if I set TouchDrawView.image = UIImage(named: "image.jpg"), when i draw and then press undo, it also removes the image I set. 
![kapture 2018-06-28 at 8 47 06](https://user-images.githubusercontent.com/16408328/42008490-06480fa6-7ab0-11e8-9267-b38671099d81.gif)

**Comment by dehli** [comment]
Thanks for following up @junestchick! I'll let you know if I make any progress with this.

**Comment by junestchick** [comment]
Hi @dehli, Have a good day, how about the progress?

**Comment by dehli** [comment]
Hey @junestchick, no progress has been made. Haven't had time to investigate it. If you have ideas as to what's wrong feel free to submit a PR!

**Comment by dehli** [comment]
Hey @junestchick, I finally got around to this. I've been very busy, but hopefully this solution will solve your problem. I've submitted a PR in #38, so if you get around to testing it I will appreciate your thoughts! I will probably make a release soon unless there are any issues with it!
