### ISSUE TITLE
exportImage with wrong image

### ISSUE THREAD

**Issue by stardustWK** [dehli/TouchDraw#41]
if TouchDrawView frame origin (x, y) is not equal to (0, 0),  
```
open func exportDrawing() -> UIImage {
        UIGraphicsBeginImageContextWithOptions(bounds.size, false, UIScreen.main.scale)
        self.image?.draw(in: frame)
        let image = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()
        return image!
    }
```
because the image draw in view.frame,  will be get a wrong image. the code should be:

```
    func exportDrawing() -> UIImage? {
        UIGraphicsBeginImageContextWithOptions(bounds.size, false, UIScreen.main.scale)
        self.image?.draw(in: bounds)
        let image = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()
        return image
    }
```

**Comment by splashdbg** [comment]
Also you should fix:

`/// Begins the image context
    func beginImageContext() {
        UIGraphicsBeginImageContextWithOptions(frame.size, false, UIScreen.main.scale)
    }`

changing it to:

`/// Begins the image context
    func beginImageContext() {
        UIGraphicsBeginImageContextWithOptions(bounds.size, false, UIScreen.main.scale)
    }`

**Comment by fl034** [comment]
Had exactly the same issue. The proposed change fixes this.
@stardustWK would lease you make a pull request? 
cc @dehli
