### ISSUE TITLE
How to save signature in UserDefault and when i open pdf next time it will set to draw method

### ISSUE THREAD

**Issue by Mahesh160393** [dehli/TouchDraw#43]
Hello @dehli  i used this pod in my project which is pdf editing tool and i want to save signature in UserDefault and next time when he open new PDF then the signature will set to draw. how can we do that. Please let me know..

Thank You In Advance

**Comment by dehli** [comment]
Hey @Mahesh160393, sorry for the late reply! You can use a combination of `exportStack` and `importStack` (you'll need to properly persist the data). Hope that helps! Cheers.

**Comment by Mahesh160393** [comment]
Thank You @dehli for reply. Let me try this and let you know.
