### ISSUE TITLE
Get Cropped image

### ISSUE THREAD

**Issue by PawanmSpaceo** [dehli/TouchDraw#44]
Currently while exporting you are giving whole image but I need cropped image I mean I what to remove white space from top and bottom
Can It will be possible for you?

**Comment by dehli** [comment]
Hi @PawanmSpaceo, this library doesn't support that use-case. You would be able to crop the `UIImage` that's returned to you though!

**Comment by PawanmSpaceo** [comment]
Ok @dehli
