### ISSUE TITLE
Create a new tag/release

### ISSUE THREAD

**Issue by richardtop** [dehli/TouchDraw#58]
Getting this error with the latest Xcode 14.3:

package 'package.swift' is using Swift tools version 3.1.0 which is no longer supported; consider using '// swift-tools-version: 5.8' to specify the current tools version

Tagging the latest master branch commit would allow SPM to see the newer release and use newer toolchain.

**Comment by dehli** [comment]
Hi, previously https://github.com/dehli/TouchDraw/pull/53 was submitted to address this. Is that what we need to do again? I don't have access to a Mac at the moment but would be open to PRs.

**Comment by richardtop** [comment]
Nope, this is a related issue. SPM cannot "see" this information when used in the versioning mode. So now I suggest adding a new "release" to the project, e.g. via "releases" tab: https://github.com/dehli/TouchDraw/releases
Then SPM would pick up the latest changes.

**Comment by dehli** [comment]
Thanks! Will get that taken care of.

**Comment by richardtop** [comment]
Thanks, looking forward to having the release in place. If that's not done, we'll have to fork the repository and support it ourselves and we'd like to avoid that.

**Comment by dehli** [comment]
Hi @richardtop I've created the new release. Let me know if the issue has been addressed and I'l go ahead and close this.

**Comment by richardtop** [comment]
Yes, the issue is fixed now.
