### ISSUE TITLE
Create a release with the latest fix for Xcode 15.0

### ISSUE THREAD

**Issue by richardtop** [dehli/TouchDraw#61]
Could you please "tag" and make a release for the latest changes in this pull request: https://github.com/dehli/TouchDraw/pull/60 since the issue is very important now (Xcode 15.0 is generally available now).

Now this requires any user to manually specify the commit instead of relying on the Swift Package Manager tag/semantic versioning support.

**Comment by dehli** [comment]
Thanks again @richardtop. Just tagged https://github.com/dehli/TouchDraw/releases/tag/2.2.0

**Comment by richardtop** [comment]
Thanks!
