### ISSUE TITLE
Make it optional to implement the delegate!

### ISSUE THREAD

**Issue by Sweeper777** [dehli/TouchDraw#8]
Can you make it optional to implement the delegate? Sometimes people want a canvas that doesn't have an undo/redo function. It's very unnecessary to implement the delegate in this case. Also, can you make some of the methods in the delegate optional to implement?

**Comment by dehli** [comment]
Hey @Sweeper777, this is a good idea and something I wanted to implement from the get go. When I first wrote this I don't think it was possible to have certain methods optional in Swift, do you know if this has changed? I'll make sure to investigate it though in either case!

**Comment by Sweeper777** [comment]
Can't you just add the `@objc` thing on the protocol and you can mark the methods `optional`? Though I admit this can make the code less swifty:

```
@objc public protocol TouchDrawViewDelegate {
    optional func undoEnabled()
    optional func undoDisabled()
    // and so on...
}
```

And you need to call those methods like this:

    delegate.undoEnabled?()

**Comment by dehli** [comment]
Hey @Sweeper777, ya that would work! I was reading through [this](http://useyourloaf.com/blog/swift-optional-protocol-methods/) to get some ideas. I'll get this implemented this weekend. :) Thanks for the feedback!

**Comment by dehli** [comment]
Hey @Sweeper777, I updated the code so the protocol is optional here: #10. I'll close this issue once I merge it to master and push the latest version to Cocoapods.

**Comment by dehli** [comment]
If you bump your version to 1.3.0 (if using CocoaPods), this should be implemented. Please let me know if you encounter any issues @Sweeper777. Thanks!
